### ISSUE TITLE
Question about initial SQL generate process

### ISSUE THREAD

**Issue by SivilTaram** [clic-lab/atis#1]
Hi Alane, thanks for your impressive work! I have a question on the section  4.5 of the paper and here is what the paper describes:

> The utterance is encoded using the initial discourse state h^I_0 , the discourse state h^I_1 is computed, the query y_1 is generated, and the set of segments S_1 is created.

I want to know the initial query y_1 is **generated by the model**, or just **passed by annotation**? If the answer is yes, is it illustrated that the model could translate plain text into SQL alone ? 

Thanks for your reply :)

**Comment by alsuhr-c** [comment]
y_1 is the query generated by the model corresponding to the first utterance x_1. 

In the first turn of the interaction, the model uses as input only the first utterance x_1 (as there have been no previously-generated queries in the interaction), and "translates" it into a SQL query (y_1). 

During full inference, ground truth queries are not used to predict subsequent queries. 

Hope this helps.

**Comment by SivilTaram** [comment]
Got it, it helps a lot! Very thanks for your reply!
