### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '../atis_data/data/resplit/processed/train_with_tables.pkl'

### ISSUE THREAD

**Issue by ar-ambuj23** [clic-lab/atis#3]
I am getting file not found error for "train_with_tables.pkl". Can you please guide me where can I find this pickle file?

**Comment by alsuhr-c** [comment]
This file is derived from data licensed by the LDC, thus you will need the LDC licenses (LDC93S5, LDC94S19, and LDC95S26) to access this data. Please contact me for more information.

**Comment by helenproj** [comment]
@alsuhr-c Hi, I am learning BERT and hope to use the ATIS dataset as the testbed. I wonder if I can get the licenses to access this data? Thank you.

**Comment by alsuhr-c** [comment]
You will need to talk to your institution (e.g., university) about acquiring the licenses. LDC's catalog is here: https://catalog.ldc.upenn.edu/
